@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.entity.boss.finalboss;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;